### ISSUE TITLE
Windows 10 using the f91cca47c36f65d339dbbdaf3285bfe8b19fce46 build

### ISSUE THREAD

**Issue by valINLO** [BGforgeNet/zax#1]
Generates the following log:

2021-12-11 11:46:09.968 | INFO     | zax_log:log:14 - start background thread
2021-12-11 11:46:09.971 | INFO     | zax_log:log:14 - started background thread
2021-12-11 11:46:09.973 | INFO     | zax_log:log:14 - start background thread
2021-12-11 11:46:09.975 | INFO     | zax_log:log:14 - started background thread
2021-12-11 11:46:09.977 | ERROR    | __main__:<module>:290 - An error has been caught in function '<module>', process 'MainProcess' (44028), thread 'MainThread' (21368):
Traceback (most recent call last):

> File "zax.py", line 290, in <module>

  File "zax.py", line 132, in __main__

  File "zax_config.py", line 10, in __init__

  File "zax_config.py", line 22, in load

UnboundLocalError: local variable 'config' referenced before assignment

**Comment by burner1024** [comment]
Well, non-release builds aren't guaranteed to work well, or even at all. Try the latest one.

**Comment by valINLO** [comment]
I understand, just wanted to have a look what this was all about. Latest commit/2a7855666a1bc4397692110c0fcfff45131fadbc has the same issue.

**Comment by burner1024** [comment]
attach full log
edit: linked commit should likely fix this

**Comment by valINLO** [comment]
That was the full log, will test when this finishes building

**Comment by valINLO** [comment]
It produced a new error:

2021-12-11 16:45:19.840 | INFO     | zax_log:log:14 - start background thread
2021-12-11 16:45:19.843 | INFO     | zax_log:log:14 - started background thread
2021-12-11 16:45:19.845 | INFO     | zax_log:log:14 - start background thread
2021-12-11 16:45:19.847 | INFO     | zax_log:log:14 - started background thread
2021-12-11 16:45:19.849 | ERROR    | __main__:<module>:305 - An error has been caught in function '<module>', process 'MainProcess' (60928), thread 'MainThread' (8716):
Traceback (most recent call last):

> File "zax.py", line 305, in <module>

  File "zax.py", line 141, in __main__

  File "zax_config.py", line 11, in __init__

KeyError: 'games'

**Comment by burner1024** [comment]
ok, this one should work

**Comment by valINLO** [comment]
Yep, it now starts, thank you!
